### PR TITLE
Upgrades @creuna-packages

### PR DESCRIPTION
**Pull request by asbjornh**
Upgrades to `4.0.1` of `@creuna/create-react-app` and patch versions of `@creuna/prompt` and `@creuna/react-scripts`

### CODE REVIEW

**Comment by pellebjerkestrand** [comment]
Maybe get rid of `Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.`? Run `yarn test` to see the message.

Or maybe we don't really know the version since it's `@creuna/create-react-app` that has React in it?

**Review by pellebjerkestrand — DISMISSED** [review]

**Comment by asbjornh** [comment]
This warning is generated by `@creuna/react-scripts`, more specifically the `to-stateless` script, which uses `eslint-plugin-react` internally. You can verify this by commenting out the two tests for stateless conversion in `test/stateful-stateless.js`

**Comment by asbjornh** [comment]
I think I'll leave this open until https://github.com/Creuna-Oslo/react-scripts/pull/16, https://github.com/Creuna-Oslo/create-react-app/pull/42 and https://github.com/Creuna-Oslo/create-react-app/pull/41 are closed and updated.

**Comment by asbjornh** [comment]
Closing this and creating new PR instead. There's a few non-`@creuna` dependencies that would be nice to upgrade

**Pull request closed without merging**
